attendance/staff/urls.py
from django.urls import path

from .views import (
    take_attendance, 
    get_students, 
    save_attendance,
    manage_attendance,
    get_attendance_dates,
    get_attendance_students,
    update_attendance,
)    

urlpatterns = [
    # take attendance
    path('attendance/take/', take_attendance, name='take-attendance'),
    path('ajax/students/fetch/', get_students, name='ajax-fetch-students'),
    path('ajax/attendance/save/', save_attendance, name='ajax-save-attendance'),
    # manage attendance
    path('attendance/', manage_attendance, name='manage-attendance'),
    path('ajax/attendance/dates/fetch/', get_attendance_dates, name='ajax-fetch-attendance-dates'),
    path('ajax/attendance/students/fetch/', get_attendance_students, name='ajax-fetch-attendance-students'),
    path('ajax/attendance/update/', update_attendance, name='ajax-update-attendance'),

]    

feed/staff/urls.py
from django.urls import path

from .views import staff_feed

# namespace = feed-staff 

urlpatterns = [
    path('staff/feed/', staff_feed, name='staff-feed'),
]

posts/urls.py
from django.urls import path

from .views import (
    # post
    post_detail,
    add_post,
    update_post,
    delete_post,
    delete_post_detail,
    # comments
    update_comment,
    delete_comment,
    comment_likes,
    CommentLikeAPIToggle,
    # likes
    post_likes,
    PostLikeAPIToggle,
)

# namespace = posts 

urlpatterns = [
    # post
    path('p/<str:post_slug>/', post_detail, name='post-detail'),
    path('p/ajax/add/', add_post, name='add-post'),
    path('p/<str:post_slug>/update/', update_post, name='update-post'),
    path('p/<str:post_slug>/delete/', delete_post, name='delete-post'),
    path('p/<str:post_slug>/detail/delete/', delete_post_detail, name='delete-post-detail'),

    # comments
    path('c/<int:comment_id>/ucdate/', update_comment, name='update-comment'),
    path('c/<int:comment_id>/delete/', delete_comment, name='delete-comment'),
    path('c/<int:comment_id>/likes/', comment_likes, name='comment-likes'),
    path('api/c/<int:comment_id>/like/', CommentLikeAPIToggle.as_view(), name='comment-like-api-toggle'),

    # likes
    path('p/<str:post_slug>/likes/', post_likes, name='post-likes'),
    path('api/p/<str:post_slug>/like/', PostLikeAPIToggle.as_view(), name='post-like-api-toggle'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static

from accounts.decorators import unauthenticated_user
from accounts.forms import (
        EmailValidationOnForgotPassword, 
        PasswordFieldsOnForgotPassword, 
        # PasswordFieldsOnChangePassword,
    )
from accounts.views import CustomPasswordResetConfirmView     

urlpatterns = [
    ## standard admin
    path('admin/', admin.site.urls),

    ## Regular Endpoints
    # Accounts
    path('', include(('accounts.urls', 'accounts'), namespace='accounts')),
    # AdminHOD
    path('', include(('adminhod.urls', 'adminhod'), namespace='adminhod')),
    # Course
    path('', include(('course.urls', 'course'), namespace='course')),
    # Staff
    path('', include(('staff.urls', 'staff'), namespace='staff')),
    # Student 
    path('', include(('student.urls', 'student'), namespace='student')),
    # Posts
    path('', include(('posts.urls', 'posts'), namespace='posts')),
    # Attendance
    path('', include(('attendance.adminhod.urls', 'attendance'), namespace='attendance-adminhod')),
    path('', include(('attendance.staff.urls', 'attendance'), namespace='attendance-staff')),
    path('', include(('attendance.student.urls', 'attendance'), namespace='attendance-student')),
    # Feedback
    path('', include(('feedback.adminhod.urls', 'feedback'), namespace='feedback-adminhod')),
    path('', include(('feedback.staff.urls', 'feedback'), namespace='feedback-staff')),
    path('', include(('feedback.student.urls', 'feedback'), namespace='feedback-student')),
    # Result
    path('', include(('result.adminhod.urls', 'result'), namespace='result-adminhod')),
    path('', include(('result.staff.urls', 'result'), namespace='result-staff')),
    path('', include(('result.student.urls', 'result'), namespace='result-student')),
    # Announcement
    path('', include(('announcement.adminhod.urls', 'announcement'), namespace='announcement-adminhod')),
    path('', include(('announcement.staff.urls', 'announcement'), namespace='announcement-staff')),
    path('', include(('announcement.student.urls', 'announcement'), namespace='announcement-student')),
    # Assignment
    path('', include(('assignment.adminhod.urls', 'assignment'), namespace='assignment-adminhod')),
    path('', include(('assignment.staff.urls', 'assignment'), namespace='assignment-staff')),
    path('', include(('assignment.student.urls', 'assignment'), namespace='assignment-student')),
    # Contact
    # path('', include(('contact.adminhod.urls', 'contact'), namespace='contact-adminhod')),
    path('', include(('contact.staff.urls', 'contact'), namespace='contact-staff')),
    path('', include(('contact.student.urls', 'contact'), namespace='contact-student')),
    # Feed
    # path('', include(('feed.adminhod.urls', 'feed'), namespace='feed-adminhod')),
    path('', include(('feed.staff.urls', 'feed'), namespace='feed-staff')),
    path('', include(('feed.student.urls', 'feed'), namespace='feed-student')),
    

    # Password reset
    # 1- Submit password form                     // PasswordResetView.as_view() 
    # 2- Email sent success message               // PasswordResetDoneView.as_view()  
    # 3- Link to password reset form in email     // PasswordResetConfirmView.as_view() 
    # 4- password successfully changed message    // PasswordResetCompleteView.as_view()

    path('password/reset/', unauthenticated_user(auth_views.PasswordResetView.as_view(
                                template_name='accounts/password_reset.html',
                                form_class=EmailValidationOnForgotPassword,)),
                                name='password_reset'),
    path('password/reset/sent/', unauthenticated_user(auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_sent.html',)), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
    #                             template_name='accounts/password_reset_form.html',
    #                             form_class=PasswordFieldsOnForgotPassword,),
    #                             name='password_reset_confirm'),
    path('reset/<uidb64>/<token>/', unauthenticated_user(CustomPasswordResetConfirmView.as_view()), name='password_reset_confirm'),                            
    path('password/reset/complete/', unauthenticated_user(auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_done.html',)), name='password_reset_complete'),

    # Password change
    # path('password_change/', auth_views.PasswordChangeView.as_view(
    #                             template_name='accounts/password_change_form.html',
    #                             form_class=PasswordFieldsOnChangePassword,),
    #                             name='password_change'),
    # path('password_change_complete/', auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html',), name='password_change_done'),
                            
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

staff/urls.py
from django.urls import path

from .views import staff_dashboard, staff_profile    

urlpatterns = [
    # dashboard
    path('dashboard/staff/', staff_dashboard, name='dashboard'),
    # staff profile
    path('staff/profiles/<str:staff_slug>/', staff_profile, name='staff-profile'),
] 

announcement/staff/views.py
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from django.db.models import Q
from django.template.loader import render_to_string

from staff.models import Staff
from course.models import Subject
from announcement.models import Announcement
from announcement.adminhod.forms import AddAnnouncementForm
from announcement.adminhod.views import add_announcement_form

# View Announcements
def view_announcements_staff(request):
    """
    Display all announcements of current staff's courses.
    """
    # get list of all staffs' ids of current staff's courses.
    staff_ids_list = Subject.objects.staff_ids(request.user, is_staff=True)
    # get list of all adminhods' ids of current staff's courses
    adminhod_ids_list = Subject.objects.courses_adminhods_ids(request.user)
    # display all announcements of current staff's courses.
    announcements = Announcement.objects.filter(
        Q(adminhod__id__in=adminhod_ids_list)|
        Q(staff__user__id__in=staff_ids_list) 
    ).distinct()
    # get current staff.
    staff = get_object_or_404(Staff, user__id=request.user.id)
    # display all announcements.
    announcements = Announcement.objects.all()
    # update announcements from not seen to be seen. 
    Announcement.objects.announcements_updated(request.user, staff_ids_list, adminhod_ids_list, is_staff=True)
    context = {'announcements':announcements, 'staff':staff}
    return render(request, 'staff/view_announcements.html', context)
   
def add_announcement_staff(request):
    """
    Add announcements.
    """
    # get current staff.
    staff = get_object_or_404(Staff, user__id=request.user.id)
    if request.method == 'POST':
        announcement_form = AddAnnouncementForm(request.POST)
    else:
        announcement_form = AddAnnouncementForm()
    return add_announcement_form(request, announcement_form, 'staff/add_announcements.html', staff=staff)

def delete_announcement_staff(request, announcement_id):
    """
    Take announcement's id, and get announcement by its id. 
    Delete this announcement.
    """
    # get announcement by its id.
    announcement = get_object_or_404(Announcement, pk=announcement_id)
    # get current staff.
    staff = get_object_or_404(Staff, user__id=request.user.id)
    data = dict()
    if announcement.staff == staff:
        if request.method == 'POST':
            # delete announcement.
            announcement.delete()
            data['form_is_valid'] = True 
            # get all announcements. 
            announcements = Announcement.objects.all()
            context = {'announcements': announcements, 'staff':staff}
            data['html_announcement_list'] = render_to_string('staff/includes/partial_announcement_list.html', context)
        else:
            context = {'announcement': announcement}
            data['html_form'] = render_to_string('staff/includes/partial_announcement_delete.html', context, request=request)
    return JsonResponse(data)    

attendance/adminhod/views.py
import json

from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt 

from course.models import Course, Subject
from student.models import SessionYear
from attendance.models import Attendance, AttendanceReport

# View Attendance
def view_attendance_adminhod(request):
    """
    Display all attendance data of current adminhod's courses.
    """
    # get all courses of current adminhod.
    courses = Course.objects.filter(adminhod__user__id=request.user.id)
    # get all session years.
    session_years = SessionYear.objects.all()
    # get first course.
    first_course = courses.first()
    # get all subjects of first course.
    subjects = Subject.objects.filter(course=first_course) 
    context = {'courses':courses, 'session_years':session_years, 'subjects':subjects}
    return render(request, 'adminhod/view_attendance.html', context)

def get_attendance_subjects(request):
    """
    Get all subjects of a selected course.
    """
    # get course id.
    course_id = request.GET.get('course')
    # check if staff assignment or not.
    is_staff_assignment = request.GET.get('is_staff_assignment')
    # get list of subjects data of current course.
    if course_id and is_staff_assignment:
        subjects_list_data = Subject.objects.get_subjects_list_data(course_id, is_staff_assignment=True)
    elif course_id:
        subjects_list_data = Subject.objects.get_subjects_list_data(course_id)
    else:
        subjects_list_data = Subject.objects.get_subjects_list_data()    
    return JsonResponse(json.dumps(subjects_list_data), content_type='application/json', safe=False) 

@csrf_exempt
def get_attendance_data_adminhod(request):
    """
    Get all attendance data for certain student and subject between range of two dates.
    """ 
    # get session year id.
    session_year_id = request.POST.get('session_id')   
    # get subject id.
    subject_id = request.POST.get('subject_id')
    # get attendance date.
    attendance_date = request.POST.get('attendance_date')
    # get attendance record of this subject, attendance date and session year.
    try:
        attendance = Attendance.objects.get(attendance_date=attendance_date, subject__id=subject_id, session_year__id=session_year_id)
    except:
        attendance = None
    # get list of attendance students for attendance record.
    attendance_students_list_data = AttendanceReport.objects.get_attendance_students_list_data(attendance)
    return JsonResponse(json.dumps(attendance_students_list_data), content_type='application/json', safe=False)

attendance/student/views.py
import json
import datetime

from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt 

from course.models import Subject
from student.models import Student
from attendance.models import Attendance, AttendanceReport

# View Attendance
def view_attendance(request):
    """
    Display all attendance data of current student. 
    """
    # get current student.
    student = get_object_or_404(Student, user__id=request.user.id)
    # get all subjects of current student's course.
    subjects = Subject.objects.filter(course=student.course)
    context = {'subjects':subjects}
    return render(request, 'student/view_attendance.html', context)

@csrf_exempt
def get_attendance_data(request):
    """
    Get all attendance data for certain student and subject between range of two dates.
    """ 
    # current student.
    student = get_object_or_404(Student, user__id=request.user.id)   
    # get subject.
    subject_id = request.POST.get('subject_id')
    subject = get_object_or_404(Subject, id=subject_id)
    # get date range.
    date_range_str = request.POST.get('date_range')
    start_date = datetime.datetime.strptime(date_range_str[:10], '%m/%d/%Y').date()
    end_date = datetime.datetime.strptime(date_range_str[13:], '%m/%d/%Y').date()
    # get attendance record of this subject and attendance date.
    attendance = Attendance.objects.filter(attendance_date__range=(start_date, end_date), subject=subject)
    # get list of attendance report data of current student.
    attendance_reports_list_data = AttendanceReport.objects.get_attendance_reports_list_data(attendance, student)
    return JsonResponse(json.dumps(attendance_reports_list_data), content_type='application/json', safe=False)

feed/staff/views.py
from django.shortcuts import render

from posts.models import Post
from course.models import Subject
from student.models import Student
from posts.utils import paginate_posts
from posts.forms import CommentForm

def staff_posts(request):
    """
    Get posts of all staffs and students of current staff's courses, including current staff's posts.
    """
    # get list of all staffs' ids of current staff's courses.
    staff_ids_list = Subject.objects.staff_ids(request.user, is_staff=True)
    # get list of all courses' ids of current staff.
    courses_ids_list = Subject.objects.courses_ids(request.user)
    # get list of all students' ids of current staff's courses.
    students_ids_list = Student.objects.filter(course__id__in=courses_ids_list).values_list('user__id', flat=True)
    return Post.objects.feed(students_ids_list, staff_ids_list)

def staff_feed(request):
    """
    Display staff's feed.
    """
    # get staff's feed.
    posts = staff_posts(request)
    # paginate staff's feed.
    page_number = request.GET.get('page', 1)
    page_obj_posts = paginate_posts(posts, page_number)
    # comment form.
    comment_form = CommentForm(auto_id=False)  
    context = {'posts':page_obj_posts, 'comment_form':comment_form}
    return render(request, 'staff/staff_feed.html', context)

attendance/templates/staff/scripts_includes/manage_attendance_js.html
{% load static %}

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- Moment -->
<script src="{% static 'plugins/moment/moment.min.js' %}"></script>
<!-- overlayScrollbars -->
<script src="{% static 'plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
<!-- SweetAlert2 -->
<script src="{% static 'plugins/sweetalert2/sweetalert2.min.js' %}"></script>
<!-- Toastr -->
<script src="{% static 'plugins/toastr/toastr.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.js' %}"></script>


<script>
    /* Constants */
    const Toast = Swal.mixin({
        toast: true,
        position: 'top-end',
        showConfirmButton: false,
        timer: 5000
    });

    $(document).ready(function () {

        /* Manage attendance */
        // fetch attendance dates
        $(document).on("click", "#fetch-attendance-date", function () {
            var subject = $('#manage-attendance-subject').val();
            var sessionYear = $('#manage-attendance-session').val();

            $.ajax({
                url: '{% url "attendance-staff:ajax-fetch-attendance-dates" %}',
                type: 'POST',
                data: { subject: subject, session_year: sessionYear },
            })
                .done(function (response) {
                    var json_data = JSON.parse(response);
                    if (json_data.length > 0) {
                        var html_data = "";
                        for (key in json_data) {
                            html_data += "<option value=" + json_data[key]["id"] + ">" + json_data[key]["attendance_date"] + "</option>";
                        }
                        $('#no-attendance-date').html("");
                        $('#no-attendance-date').hide();
                        $('#attendance-date-data').show();
                        $("#fetch-manage-students").show();
                        $("#manage-attendance-date").html(html_data);
                    }
                    else {
                        $('#no-attendance-date').html("<b>No Attendance Dates</b>");
                        $('#no-attendance-date').show();
                        $('#attendance-date-data').hide();
                        $("#fetch-manage-students").hide();
                        $("#manage-attendance-date").html("");
                    }

                })
                .fail(function () {
                    Toast.fire({
                        type: 'error',
                        title: 'Error in fetching attendance dates. Please try again.'
                    })
                    $('#no-attendance-date').html("");
                    $('#no-attendance-date').hide();
                    $('#attendance-date-data').hide();
                    $("#fetch-manage-students").hide();
                })
        });
        // fetch students
        $(document).on("click", "#fetch-manage-students-btn", function () {
            var attendanceId = $('#manage-attendance-date').val();

            $.ajax({
                url: '{% url "attendance-staff:ajax-fetch-attendance-students" %}',
                type: 'POST',
                data: { attendance_id: attendanceId },
            })
                .done(function (response) {
                    var json_data = JSON.parse(response);
                    var div_data = "<div class='form-group'><label>Student Attendance</label></div>";
                    div_data += "<div class='form-group'><div class='row'>";
                    for (key in json_data) {
                        div_data += "<div class='col-lg-4'><div class='form-check mt-2'><input type='checkbox' id='checkbox'"
                        if (json_data[key]['status']) {
                            div_data += "checked='checked'";
                        }
                        else {
                            div_data += "";
                        }
                        div_data += "name='manage-student-data[]' value='" + json_data[key]['id'] + "'><label class='form-check-label ml-1'>" + json_data[key]['name'] + "</label></div></div>";
                    }
                    div_data += "</div></div>";
                    div_data += "<div class='form-group'>";
                    div_data += "<button name='update-attendance' class='btn btn-success btn-block' id='update-attendance'>Update Attendance</button>"
                    div_data += "</div>";
                    $('#manage-student-data').html(div_data)
                    $('#manage-student-data').show();
                })
                .fail(function () {
                    Toast.fire({
                        type: 'error',
                        title: 'Error in fetching students. Please try again.'
                    })
                })
        });

        // update attendance
        $(document).on("click", "#update-attendance", function () {
            // return all checkbox data as an array
            var studentData = $('input[name="manage-student-data[]"]').map(function () {
                if ($(this).is(":checked")) {
                    // student is present
                    return { "id": $(this).val(), "status": 1 };
                }
                else {
                    // student is absent
                    return { "id": $(this).val(), "status": 0 };
                }
            }).get()
            var attendanceId = $('#manage-attendance-date').val();
            // convert student data to json format 
            studentData = JSON.stringify(studentData)

            $.ajax({
                url: '{% url "attendance-staff:ajax-update-attendance" %}',
                type: 'POST',
                data: { student_data: studentData, attendance_id: attendanceId },
            })
                .done(function (response) {
                    if (response == 'Ok') {
                        $("#success-update-attendance").html("Attendance has been updated successfully.");
                        $("#success-update-attendance").show();
                        setTimeout(function () { $('.message').fadeOut('slow'); }, 5000); // <-- time in milliseconds, 1000 =  1 sec
                    }
                    else {
                        $("#error-update-attendance").html("Error in saving attendance data. Please try again.");
                        $("#error-update-attendance").show();
                        setTimeout(function () { $('.message').fadeOut('slow'); }, 5000);
                    }
                    $('#manage-student-data').hide();
                    $(window).scrollTop(0);
                })
                .fail(function () {
                    Toast.fire({
                        type: 'error',
                        title: 'Error in saving attendance data. Please try again.'
                    })
                })
        });

    });

</script>

attendance/templates/staff/scripts_includes/take_attendance_js.html
{% load static %}

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- Moment -->
<script src="{% static 'plugins/moment/moment.min.js' %}"></script>
<!-- overlayScrollbars -->
<script src="{% static 'plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
<!-- SweetAlert2 -->
<script src="{% static 'plugins/sweetalert2/sweetalert2.min.js' %}"></script>
<!-- Toastr -->
<script src="{% static 'plugins/toastr/toastr.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.js' %}"></script>


<script>
    /* Constants */
    const Toast = Swal.mixin({
        toast: true,
        position: 'top-end',
        showConfirmButton: false,
        timer: 5000
    });

    $(document).ready(function () {
        /* Take attendance */
        
        // fetch students
        $(document).on("click", "#fetch-student", function () {
            var subject = $('#attendance-subject').val();
            var sessionYear = $('#attendance-session').val();

            $.ajax({
                url: '{% url "attendance-staff:ajax-fetch-students" %}',
                type: 'POST',
                data: { subject: subject, session_year: sessionYear },
            })
                .done(function (response) {
                    var json_data = JSON.parse(response);
                    var div_data = "<div class='form-group'><label>Attendance date (mm/dd/yyyy)</label><input type='date' name='attendance-date' class='form-control' id='attendance-date' value='' required></div>";
                    div_data += "<div class='form-group'><label>Student Attendance</label></div>";
                    div_data += "<div class='form-group'><div class='row'>";
                    for (key in json_data) {
                        div_data += "<div class='col-lg-4'><div class='form-check mt-2'><input type='checkbox' checked='checked' name='student_data[]' value='"+json_data[key]['id']+"'><label class='form-check-label ml-1'>"+json_data[key]['name']+"</label></div></div>";
                    }
                    div_data += "</div></div>";
                    div_data += "<div class='form-group'>";
                    div_data += "<button name='save-attendance' class='btn btn-success btn-block' id='save-attendance'>Save Attendance</button>"
                    div_data += "</div>";
                    $('#student-data').html(div_data)
                    $('#student-data').show();
                    // get the current date and convert to 2014-07-10
                    var todayDate = moment().format("YYYY-MM-DD");
                    // set attendance default value to today
                    $('#attendance-date').val(todayDate);
                })
                .fail(function () {
                    Toast.fire({
                        type: 'error',
                        title: 'Error in fetching students. Please try again.'
                    })
                })
            
            // save attendance
            $(document).on("click", "#save-attendance", function () {
                // return all checkbox data as an array
                var studentData = $('input[name="student_data[]"]').map(function () {
                    if ($(this).is(":checked")) {
                        // student is present
                        return { "id": $(this).val(), "status": 1 };
                    }
                    else {
                        // student is absent
                        return { "id": $(this).val(), "status": 0 };
                    }
                }).get()
                var attendanceDate = $('#attendance-date').val();
                var subject = $('#attendance-subject').val()
                var sessionYear = $('#attendance-session').val()
                // convert student data to json format 
                studentData = JSON.stringify(studentData)

                $.ajax({
                    url: '{% url "attendance-staff:ajax-save-attendance" %}',
                    type: 'POST',
                    data: { student_data: studentData, attendance_date: attendanceDate, subject: subject, session_year: sessionYear },
                })
                    .done(function (response) {
                        $(window).scrollTop(0);
                        if (response == 'CREATED') {
                            $("#success-save-attendance").html("Attendance has been saved successfully.");
                            $("#success-save-attendance").show();
                            setTimeout(function () { $('.message').fadeOut('slow'); }, 5000); // <-- time in milliseconds, 1000 =  1 sec
                        }
                        else if (response == 'EXISTS'){
                            $("#attendance-exists").html("This attendance record already exists.");
                            $("#attendance-exists").show();
                            setTimeout(function () { $('.message').fadeOut('slow'); }, 5000); // <-- time in milliseconds, 1000 =  1 sec
                        }
                        else {
                            $("#error-save-attendance").html("Error in saving attendance data. Please try again.");
                            $("#error-save-attendance").show();
                            setTimeout(function () { $('.message').fadeOut('slow'); }, 5000);
                        }
                        $(window).scrollTop(0);
                        $('#student-data').load();
                    })
                    .fail(function () {
                        Toast.fire({
                            type: 'error',
                            title: 'Error in saving attendance data. Please try again.'
                        })
                    })
            });
        });

    });

</script>