accounts/urls.py
from django.urls import path

from .views import (
    user_login_view, 
    user_logout_view, 
    change_password, 
    change_password_done,
    validate_email_view,
    validate_email_update_view
)

# namespace = accounts

urlpatterns = [
    # Authentication
    path('login/', user_login_view, name='login'),
    path('logout/', user_logout_view, name='logout'),
    path('password/change/', change_password, name='password-change'),
    path('password/change/done/', change_password_done, name='password-change-done'),

    # js validations
    path('ajax/validate/email/', validate_email_view, name='ajax-validate-email'),
    path('ajax/validate/email/<int:user_id>/update/', validate_email_update_view, name='ajax-validate-email-update'),
]    

adminhod/staff/urls.py
from django.urls import path

from .views import (
    add_staff, 
    manage_staff,
    paginate_staff,
    filter_staff,
    update_staff,
    delete_staff,
)    

# namespace = adminhod

urlpatterns = [
    # staff
    path('staff/add/', add_staff, name='add-staff'),
    path('staff/', manage_staff, name='manage-staff'),
    path('ajax/staff/paginate/', paginate_staff, name='ajax-paginate-staff'),
    path('ajax/staff/filter/', filter_staff, name='ajax-filter-staff'),
    path('staff/<int:staff_id>/update/', update_staff, name='update-staff'),
    path('staff/<int:staff_id>/delete/', delete_staff, name='delete-staff'),
]    

adminhod/student/urls.py
from django.urls import path

from .views import (
    add_student, 
    manage_student,
    paginate_student,
    filter_student,
    update_student,
    delete_student,
    
)    

# namespace = adminhod

urlpatterns = [
    # student
    path('students/add/', add_student, name='add-student'),
    path('students/', manage_student, name='manage-student'),
    path('ajax/students/paginate/', paginate_student, name='ajax-paginate-students'),
    path('ajax/students/filter/', filter_student, name='ajax-filter-students'),
    path('students/<int:student_id>/update/', update_student, name='update-student'),
    path('students/<int:student_id>/delete/', delete_student, name='delete-student'),
] 

adminhod/urls.py
from django.urls import path, include

from .views import admin_dashboard, update_adminhod_view 

# namespace = adminhod

urlpatterns = [
    # dashboard
    path('', admin_dashboard, name='dashboard'),
    # update student profile
    path('profile/update/', update_adminhod_view, name='update-adminhod-profile'),

    path('', include('adminhod.staff.urls')),
    path('', include('adminhod.student.urls')),
    path('', include('adminhod.session.urls')),
]    

course/urls.py
from django.urls import path

from .views import (
    # course
    add_course, 
    manage_course,
    paginate_course,
    update_course,
    delete_course,
    # subject 
    add_subject, 
    manage_subject,
    paginate_subject,
    filter_subject,
    update_subject,
    delete_subject,
)     

# namespace = course 

urlpatterns = [
    # course
    path('courses/add/', add_course, name='add-course'),
    path('courses/', manage_course, name='manage-course'),
    path('ajax/courses/paginate/', paginate_course, name='ajax-paginate-courses'),
    path('courses/<int:course_id>/update/', update_course, name='update-course'),
    path('courses/<int:course_id>/delete/', delete_course, name='delete-course'),
    # subject
    path('subjects/add/', add_subject, name='add-subject'),
    path('subjects/', manage_subject, name='manage-subject'),
    path('ajax/subjects/paginate/', paginate_subject, name='ajax-paginate-subjects'),
    path('ajax/subjects/filter/', filter_subject, name='ajax-filter-subjects'),
    path('subjects/<int:subject_id>/update/', update_subject, name='update-subject'),
    path('subjects/<int:subject_id>/delete/', delete_subject, name='delete-subject'),
]    

posts/urls.py
from django.urls import path

from .views import (
    # post
    post_detail,
    add_post,
    update_post,
    delete_post,
    delete_post_detail,
    # comments
    update_comment,
    delete_comment,
    comment_likes,
    CommentLikeAPIToggle,
    # likes
    post_likes,
    PostLikeAPIToggle,
)

# namespace = posts 

urlpatterns = [
    # post
    path('p/<str:post_slug>/', post_detail, name='post-detail'),
    path('p/ajax/add/', add_post, name='add-post'),
    path('p/<str:post_slug>/update/', update_post, name='update-post'),
    path('p/<str:post_slug>/delete/', delete_post, name='delete-post'),
    path('p/<str:post_slug>/detail/delete/', delete_post_detail, name='delete-post-detail'),

    # comments
    path('c/<int:comment_id>/ucdate/', update_comment, name='update-comment'),
    path('c/<int:comment_id>/delete/', delete_comment, name='delete-comment'),
    path('c/<int:comment_id>/likes/', comment_likes, name='comment-likes'),
    path('api/c/<int:comment_id>/like/', CommentLikeAPIToggle.as_view(), name='comment-like-api-toggle'),

    # likes
    path('p/<str:post_slug>/likes/', post_likes, name='post-likes'),
    path('api/p/<str:post_slug>/like/', PostLikeAPIToggle.as_view(), name='post-like-api-toggle'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static

from accounts.decorators import unauthenticated_user
from accounts.forms import (
        EmailValidationOnForgotPassword, 
        PasswordFieldsOnForgotPassword, 
        # PasswordFieldsOnChangePassword,
    )
from accounts.views import CustomPasswordResetConfirmView     

urlpatterns = [
    ## standard admin
    path('admin/', admin.site.urls),

    ## Regular Endpoints
    # Accounts
    path('', include(('accounts.urls', 'accounts'), namespace='accounts')),
    # AdminHOD
    path('', include(('adminhod.urls', 'adminhod'), namespace='adminhod')),
    # Course
    path('', include(('course.urls', 'course'), namespace='course')),
    # Staff
    path('', include(('staff.urls', 'staff'), namespace='staff')),
    # Student 
    path('', include(('student.urls', 'student'), namespace='student')),
    # Posts
    path('', include(('posts.urls', 'posts'), namespace='posts')),
    # Attendance
    path('', include(('attendance.adminhod.urls', 'attendance'), namespace='attendance-adminhod')),
    path('', include(('attendance.staff.urls', 'attendance'), namespace='attendance-staff')),
    path('', include(('attendance.student.urls', 'attendance'), namespace='attendance-student')),
    # Feedback
    path('', include(('feedback.adminhod.urls', 'feedback'), namespace='feedback-adminhod')),
    path('', include(('feedback.staff.urls', 'feedback'), namespace='feedback-staff')),
    path('', include(('feedback.student.urls', 'feedback'), namespace='feedback-student')),
    # Result
    path('', include(('result.adminhod.urls', 'result'), namespace='result-adminhod')),
    path('', include(('result.staff.urls', 'result'), namespace='result-staff')),
    path('', include(('result.student.urls', 'result'), namespace='result-student')),
    # Announcement
    path('', include(('announcement.adminhod.urls', 'announcement'), namespace='announcement-adminhod')),
    path('', include(('announcement.staff.urls', 'announcement'), namespace='announcement-staff')),
    path('', include(('announcement.student.urls', 'announcement'), namespace='announcement-student')),
    # Assignment
    path('', include(('assignment.adminhod.urls', 'assignment'), namespace='assignment-adminhod')),
    path('', include(('assignment.staff.urls', 'assignment'), namespace='assignment-staff')),
    path('', include(('assignment.student.urls', 'assignment'), namespace='assignment-student')),
    # Contact
    # path('', include(('contact.adminhod.urls', 'contact'), namespace='contact-adminhod')),
    path('', include(('contact.staff.urls', 'contact'), namespace='contact-staff')),
    path('', include(('contact.student.urls', 'contact'), namespace='contact-student')),
    # Feed
    # path('', include(('feed.adminhod.urls', 'feed'), namespace='feed-adminhod')),
    path('', include(('feed.staff.urls', 'feed'), namespace='feed-staff')),
    path('', include(('feed.student.urls', 'feed'), namespace='feed-student')),
    

    # Password reset
    # 1- Submit password form                     // PasswordResetView.as_view() 
    # 2- Email sent success message               // PasswordResetDoneView.as_view()  
    # 3- Link to password reset form in email     // PasswordResetConfirmView.as_view() 
    # 4- password successfully changed message    // PasswordResetCompleteView.as_view()

    path('password/reset/', unauthenticated_user(auth_views.PasswordResetView.as_view(
                                template_name='accounts/password_reset.html',
                                form_class=EmailValidationOnForgotPassword,)),
                                name='password_reset'),
    path('password/reset/sent/', unauthenticated_user(auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_sent.html',)), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
    #                             template_name='accounts/password_reset_form.html',
    #                             form_class=PasswordFieldsOnForgotPassword,),
    #                             name='password_reset_confirm'),
    path('reset/<uidb64>/<token>/', unauthenticated_user(CustomPasswordResetConfirmView.as_view()), name='password_reset_confirm'),                            
    path('password/reset/complete/', unauthenticated_user(auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_done.html',)), name='password_reset_complete'),

    # Password change
    # path('password_change/', auth_views.PasswordChangeView.as_view(
    #                             template_name='accounts/password_change_form.html',
    #                             form_class=PasswordFieldsOnChangePassword,),
    #                             name='password_change'),
    # path('password_change_complete/', auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html',), name='password_change_done'),
                            
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminhod/student/views.py
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from django.db.models import Q
from django.template.loader import render_to_string
from django.views.decorators.csrf import csrf_exempt 

from student.models import Student, SessionYear 
from course.models import Course
from adminhod.utils import search, paginate
from adminhod.staff.views import add_staff_student_form, update_staff_student_form
from .forms import AddStudentForm, UpdateStudentAdminForm
from .utils import filter_students


def add_student(request):
    """
    Add student.
    """
    user_type = 'STUDENT'
    if request.method == 'POST':
        student_form = AddStudentForm(request.POST, request.FILES, request=request)
    else:
        student_form = AddStudentForm(request=request)
    return add_staff_student_form(request, student_form, 'student/add_student.html', user_type)

def manage_student(request):
    """
    Display all students of current adminhod's courses.
    Search students of current adminhod by name or email, ordered alphabetically by name.
    """
    # get all courses of current adminhod.
    courses = Course.objects.filter(adminhod__user__id=request.user.id)
    # get all students of current adminhod's courses. 
    students_qs = Student.objects.filter(course__in=courses).order_by('course')
    # get all sessions.
    session_years = SessionYear.objects.all()
    # paginate the students list.
    page_obj_students = paginate(students_qs)
    if request.is_ajax():
        # get entered value in search input field.
        q = request.GET.get('search').strip()
        data = dict()  
        # filter students by name or email, ordered alphabetically by name.
        students = search(q, students_qs)
        # paginate the students list.
        page_obj_students = paginate(students)    
        context = {'students': page_obj_students, 'request':request}
        data['html_student_list'] = render_to_string('student/includes/partial_student_list.html', context)
        data['html_student_pagination'] = render_to_string('student/includes/partial_student_pagination.html', context)
        return JsonResponse(data)
    context = {'students':page_obj_students, 'courses':courses, 'session_years':session_years}
    return render(request, 'student/manage_student.html', context)

@csrf_exempt
def paginate_student(request):
    """
    Paginate all students of current adminhod's courses.
    """
    # get list of all courses' ids of current adminhod.
    courses_ids_list = Course.objects.filter(adminhod__user__id=request.user.id).values_list('id', flat=True)
    # get all students of current adminhod's courses. 
    students_qs = Student.objects.filter(course__id__in=courses_ids_list).order_by('course')
    # get page number of paginator.
    page_number = request.GET.get('page').split('&')[0]
    # get course id.
    course_id = request.GET.get('course_id')
    # get session year id.
    session_year_id = request.GET.get('session_year_id')
    # get student gender.
    gender = request.GET.get('gender')
    # get list of submitted data.
    list_data = [course_id, session_year_id, gender]
    data = dict()
    # paginate the search results.
    if request.GET.get('search'):
        # get entered value in search input field.
        q = request.GET.get('search').strip()
        # filter students of current adminhod  by name or email, ordered alphabetically by name.
        students = search(q, students_qs)
        # paginate the students list.
        page_obj_students = paginate(students, page_number)
    # paginate the filter results.
    elif any(list_data):
        students = filter_students(
            course_id=course_id, 
            session_year_id=session_year_id, 
            gender=gender, 
            courses_ids_list=courses_ids_list
        )
        # paginate the students list.
        page_obj_students = paginate(students, page_number)
    else:
        # paginate the students list.
        page_obj_students = paginate(students_qs, page_number)    
    context = {'students':page_obj_students, 'request':request}
    data['html_student_list'] = render_to_string('student/includes/partial_student_list.html', context)
    data['html_student_pagination'] = render_to_string('student/includes/partial_student_pagination.html', context)    
    return JsonResponse(data)

@csrf_exempt
def filter_student(request):
    """
    Filter students by Course, Session or Gender.
    """
    # get course id.
    course_id = request.POST.get('course_id')
    # get session year id.
    session_year_id = request.POST.get('session_year_id')
    # get student gender.
    gender = request.POST.get('gender')
    # get list of all courses' ids of current adminhod.
    courses_ids_list = Course.objects.filter(adminhod__user__id=request.user.id).values_list('id', flat=True)
    data = dict()
    # filter students by Course, Session or Gender.
    students_qs = filter_students(
        course_id=course_id, 
        session_year_id=session_year_id, 
        gender=gender, 
        courses_ids_list=courses_ids_list
    )    
    if students_qs:
        # paginate the students list.
        page_obj_students = paginate(students_qs)
        context = {'students':page_obj_students, 'request':request}
    else:
        context = {'students':students_qs, 'request':request}          
    data['html_student_list'] = render_to_string('student/includes/partial_student_list.html', context)
    data['html_student_pagination'] = render_to_string('student/includes/partial_student_pagination.html', context)    
    return JsonResponse(data)
    
def update_student(request, student_id):
    """
    Take student's id, and get this student by its id.
    Update this student.
    """
    # get student by its id.
    student = get_object_or_404(Student, pk=student_id)
    if request.method == 'POST':
        student_form = UpdateStudentAdminForm(request.POST, request.FILES, request=request, instance=student)
    else:
        student_form = UpdateStudentAdminForm(request=request, instance=student, initial={'course': student.course})
    return update_staff_student_form(request, student_form, 'student/includes/partial_student_update.html', student)

def delete_student(request, student_id):
    """
    Take student's id, and get this student by its id.
    Delete this student.
    """
    # get student by its id
    student = get_object_or_404(Student, pk=student_id)
    data = dict()
    if request.method == 'POST':
        data['student_name'] = student.user.full_name
        # delete student.
        student.delete()
        data['form_is_valid'] = True 
        data['is_update'] = False 
        students = Student.objects.all()
        data['html_student_list'] = render_to_string('student/includes/partial_student_list.html', {'students': students})
    else:
        context = {'student': student}
        data['html_form'] = render_to_string('student/includes/partial_student_delete.html', context, request=request)
    return JsonResponse(data)    

adminhod/templates/adminhod/dashboard_includes/content_header.html
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Home</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{% url 'adminhod:dashboard' %}">Home</a></li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

adminhod/templates/adminhod/dashboard_includes/footer.html
<footer class="main-footer">
    <strong>Copyright &copy; 2021 <a href="https://github.com/OmarFateh">Fateh.jr</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
        <b>Version</b> 3.0.2
    </div>
</footer>

adminhod/templates/adminhod/dashboard_includes/left_navbar.html
<!-- Left navbar links -->
<ul class="navbar-nav">
    <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'adminhod:dashboard' %}" class="nav-link">Student Management System | Admin Panel</a>
    </li>
</ul>

adminhod/templates/adminhod/dashboard_includes/main_content.html
{% load static %}

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="row">
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-info">
                    <div class="inner">
                        <h3>{{ courses_total }}</h3>

                        <p>Total Courses</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-stats-bars"></i>
                    </div>
                    <a href="{% url 'course:manage-course' %}" class="small-box-footer">More info 
                        <i class="fas fa-arrow-circle-right"></i>
                    </a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-success">
                    <div class="inner">
                        <h3>{{ subjects_total }}</h3>

                        <p>Total Subjects</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-stats-bars"></i>
                    </div>
                    <a href="{% url 'course:manage-subject' %}" class="small-box-footer">More info 
                        <i class="fas fa-arrow-circle-right"></i>
                    </a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-secondary">
                    <div class="inner">
                        <h3>{{ staff_total }}</h3>

                        <p>Total Staff</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-stats-bars"></i>
                    </div>
                    <a href="{% url 'adminhod:manage-staff' %}" class="small-box-footer">More info 
                        <i class="fas fa-arrow-circle-right"></i>
                    </a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-danger">
                    <div class="inner">
                        <h3>{{ students_total }}</h3>

                        <p>Total Students</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-stats-bars"></i>
                    </div>
                    <a href="{% url 'adminhod:manage-student' %}" class="small-box-footer">More info <i
                            class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
        </div>
        <!-- /.row -->
        <!-- /.row -->
        <div class="row">
            <div class="col-lg-6">
                <!-- DONUT CHART -->
                <div class="card card-danger">
                    <div class="card-header">
                    <h3 class="card-title">Total Subjects in Course</h3>
    
                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i></button>
                    </div>
                    </div>
                    <div class="card-body">
                    <canvas id="donutChart" style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%;"></canvas>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>

            <div class="col-lg-6">
                <!-- PIE CHART -->
                <div class="card card-info">
                    <div class="card-header">
                        <h3 class="card-title">Total Students in Course</h3>

                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                            <button type="button" class="btn btn-tool" data-card-widget="remove">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-body">
                        <canvas id="pieChart1"
                            style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%;"></canvas>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>

            <div class="col-lg-6">
                <!-- PIE CHART -->
                <div class="card card-orange">
                    <div class="card-header">
                        <h3 class="card-title">Staff Feedback Statistics</h3>

                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                            <button type="button" class="btn btn-tool" data-card-widget="remove">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-body">
                        <canvas id="pieChart2"
                            style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%;"></canvas>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            
            <div class="col-lg-6">
                <!-- PIE CHART -->
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">Student Feedback Statistics</h3>

                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                            <button type="button" class="btn btn-tool" data-card-widget="remove">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-body">
                        <canvas id="pieChart3"
                            style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%;"></canvas>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>

            <div class="col-lg-12">
                <!-- BAR CHART -->
                <div class="card card-green">
                    <div class="card-header">
                        <h3 class="card-title">Attendance Statistics</h3>

                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse"><i
                                    class="fas fa-minus"></i>
                            </button>
                            <button type="button" class="btn btn-tool" data-card-widget="remove"><i
                                    class="fas fa-times"></i></button>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="chart">
                            <canvas id="barChart"
                                style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%;"></canvas>
                        </div>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<!-- /.content -->

adminhod/templates/adminhod/dashboard_includes/notifications_dropdown.html
<li class="nav-item dropdown">
    <a class="nav-link" data-toggle="dropdown" href="#">
        <span class="font-weight-bold">Settings</span>
        <i class="fas fa-user-cog ml-1"></i>
    </a>
    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <div class="dropdown-divider"></div>
        <a href="{% url 'adminhod:update-adminhod-profile' %}" class="dropdown-item">
            <i class="nav-icon fas fa-user mr-2"></i>  Edit Profile
        </a>
        <div class="dropdown-divider"></div>
        <a href="{% url 'accounts:password-change' %}" class="dropdown-item">
            <i class="nav-icon fas fa-lock mr-2"></i>  Change Password
        </a>
        <div class="dropdown-divider"></div>
        <a href="{% url 'accounts:logout' %}" class="dropdown-item">
            <i class="nav-icon fas fa-sign-out-alt mr-2"></i> LogOut
        </a>
    </div>
</li>