feed/staff/urls.py
from django.urls import path

from .views import staff_feed

# namespace = feed-staff 

urlpatterns = [
    path('staff/feed/', staff_feed, name='staff-feed'),
]

posts/urls.py
from django.urls import path

from .views import (
    # post
    post_detail,
    add_post,
    update_post,
    delete_post,
    delete_post_detail,
    # comments
    update_comment,
    delete_comment,
    comment_likes,
    CommentLikeAPIToggle,
    # likes
    post_likes,
    PostLikeAPIToggle,
)

# namespace = posts 

urlpatterns = [
    # post
    path('p/<str:post_slug>/', post_detail, name='post-detail'),
    path('p/ajax/add/', add_post, name='add-post'),
    path('p/<str:post_slug>/update/', update_post, name='update-post'),
    path('p/<str:post_slug>/delete/', delete_post, name='delete-post'),
    path('p/<str:post_slug>/detail/delete/', delete_post_detail, name='delete-post-detail'),

    # comments
    path('c/<int:comment_id>/ucdate/', update_comment, name='update-comment'),
    path('c/<int:comment_id>/delete/', delete_comment, name='delete-comment'),
    path('c/<int:comment_id>/likes/', comment_likes, name='comment-likes'),
    path('api/c/<int:comment_id>/like/', CommentLikeAPIToggle.as_view(), name='comment-like-api-toggle'),

    # likes
    path('p/<str:post_slug>/likes/', post_likes, name='post-likes'),
    path('api/p/<str:post_slug>/like/', PostLikeAPIToggle.as_view(), name='post-like-api-toggle'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static

from accounts.decorators import unauthenticated_user
from accounts.forms import (
        EmailValidationOnForgotPassword, 
        PasswordFieldsOnForgotPassword, 
        # PasswordFieldsOnChangePassword,
    )
from accounts.views import CustomPasswordResetConfirmView     

urlpatterns = [
    ## standard admin
    path('admin/', admin.site.urls),

    ## Regular Endpoints
    # Accounts
    path('', include(('accounts.urls', 'accounts'), namespace='accounts')),
    # AdminHOD
    path('', include(('adminhod.urls', 'adminhod'), namespace='adminhod')),
    # Course
    path('', include(('course.urls', 'course'), namespace='course')),
    # Staff
    path('', include(('staff.urls', 'staff'), namespace='staff')),
    # Student 
    path('', include(('student.urls', 'student'), namespace='student')),
    # Posts
    path('', include(('posts.urls', 'posts'), namespace='posts')),
    # Attendance
    path('', include(('attendance.adminhod.urls', 'attendance'), namespace='attendance-adminhod')),
    path('', include(('attendance.staff.urls', 'attendance'), namespace='attendance-staff')),
    path('', include(('attendance.student.urls', 'attendance'), namespace='attendance-student')),
    # Feedback
    path('', include(('feedback.adminhod.urls', 'feedback'), namespace='feedback-adminhod')),
    path('', include(('feedback.staff.urls', 'feedback'), namespace='feedback-staff')),
    path('', include(('feedback.student.urls', 'feedback'), namespace='feedback-student')),
    # Result
    path('', include(('result.adminhod.urls', 'result'), namespace='result-adminhod')),
    path('', include(('result.staff.urls', 'result'), namespace='result-staff')),
    path('', include(('result.student.urls', 'result'), namespace='result-student')),
    # Announcement
    path('', include(('announcement.adminhod.urls', 'announcement'), namespace='announcement-adminhod')),
    path('', include(('announcement.staff.urls', 'announcement'), namespace='announcement-staff')),
    path('', include(('announcement.student.urls', 'announcement'), namespace='announcement-student')),
    # Assignment
    path('', include(('assignment.adminhod.urls', 'assignment'), namespace='assignment-adminhod')),
    path('', include(('assignment.staff.urls', 'assignment'), namespace='assignment-staff')),
    path('', include(('assignment.student.urls', 'assignment'), namespace='assignment-student')),
    # Contact
    # path('', include(('contact.adminhod.urls', 'contact'), namespace='contact-adminhod')),
    path('', include(('contact.staff.urls', 'contact'), namespace='contact-staff')),
    path('', include(('contact.student.urls', 'contact'), namespace='contact-student')),
    # Feed
    # path('', include(('feed.adminhod.urls', 'feed'), namespace='feed-adminhod')),
    path('', include(('feed.staff.urls', 'feed'), namespace='feed-staff')),
    path('', include(('feed.student.urls', 'feed'), namespace='feed-student')),
    

    # Password reset
    # 1- Submit password form                     // PasswordResetView.as_view() 
    # 2- Email sent success message               // PasswordResetDoneView.as_view()  
    # 3- Link to password reset form in email     // PasswordResetConfirmView.as_view() 
    # 4- password successfully changed message    // PasswordResetCompleteView.as_view()

    path('password/reset/', unauthenticated_user(auth_views.PasswordResetView.as_view(
                                template_name='accounts/password_reset.html',
                                form_class=EmailValidationOnForgotPassword,)),
                                name='password_reset'),
    path('password/reset/sent/', unauthenticated_user(auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_sent.html',)), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
    #                             template_name='accounts/password_reset_form.html',
    #                             form_class=PasswordFieldsOnForgotPassword,),
    #                             name='password_reset_confirm'),
    path('reset/<uidb64>/<token>/', unauthenticated_user(CustomPasswordResetConfirmView.as_view()), name='password_reset_confirm'),                            
    path('password/reset/complete/', unauthenticated_user(auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_done.html',)), name='password_reset_complete'),

    # Password change
    # path('password_change/', auth_views.PasswordChangeView.as_view(
    #                             template_name='accounts/password_change_form.html',
    #                             form_class=PasswordFieldsOnChangePassword,),
    #                             name='password_change'),
    # path('password_change_complete/', auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html',), name='password_change_done'),
                            
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

staff/urls.py
from django.urls import path

from .views import staff_dashboard, staff_profile    

urlpatterns = [
    # dashboard
    path('dashboard/staff/', staff_dashboard, name='dashboard'),
    # staff profile
    path('staff/profiles/<str:staff_slug>/', staff_profile, name='staff-profile'),
] 

adminhod/staff/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.http import JsonResponse, HttpResponse
from django.core.mail import EmailMessage, BadHeaderError
from django.template.loader import render_to_string
from django.views.decorators.csrf import csrf_exempt 

from accounts.forms import UserAddForm, UpdateUserForm
from accounts.models import User 
from accounts.utils import unique_password_generator
from student.models import Student
from staff.models import Staff
from course.models import Course, Subject
from adminhod.utils import search, paginate 
from .forms import AddStaffForm, UpdateStaffAdminForm
from .utils import filter_staffs


def add_staff_student_form(request, form, template_name, user_type):
    """
    Take form, template name, and user's type.
    Add staff in case of taking user's type is staff.
    Add student in case of taking user's type is student.
    """
    # display user form.
    user_form = UserAddForm(request.POST or None)
    is_admin = True
    # check if the request method is post.
    if request.method == "POST":
        # if the user form and profile form are valid.
        if user_form.is_valid() and form.is_valid():
            # fetch submitted data.
            full_name = user_form.cleaned_data.get("full_name")
            email = user_form.cleaned_data.get("email")
            # generate unique password.
            password = unique_password_generator()
            # create new user.
            new_user = User.objects.create(
                full_name = full_name,
                email = email,
                user_type = user_type,
            )
            new_user.set_password(password)
            new_user.save()
            # send email to new user with email and password.
            # EmailMessage( subject, message, email_from, recipient_list )
            try:
                email = EmailMessage(
                    f'Welcome {full_name} to Student Management System', # subject  
                    f"""Hello {full_name}, 
                    \n \nyour account has been added successfully to Student Management System,
                    and here is your data: 
                    \nEmail: {email} \nPassword: {password}\n \n \n \nBest Regards \nStudent Management System Team""", # message
                    'fatehomar0@gmail.com', # from email
                    [email,] # to email list
                )
                email.send(fail_silently=False)
            except BadHeaderError:
                return HttpResponse('Invalid header found.')  
            # create new student.
            if user_type == 'STUDENT':
                new_user.student.course = form.cleaned_data.get("course")
                new_user.student.photo = form.cleaned_data.get("photo")
                new_user.student.birth_date = form.cleaned_data.get("birth_date")
                new_user.student.nationality = form.cleaned_data.get("nationality")
                new_user.student.phone = form.cleaned_data.get("phone")
                new_user.student.address = form.cleaned_data.get("address")
                new_user.student.gender = form.cleaned_data.get("gender")
                new_user.student.session_year = form.cleaned_data.get("session_year")
                new_user.student.save()
                # Display success message.
                messages.success(request, f'New student "{full_name}" has been added successfully.', extra_tags='add-student')
                # if save and add another.
                if 'save_and_add_another' in request.POST:
                    # redirect to add students url.
                    return redirect('adminhod:add-student')
                # if save.
                elif 'save' in request.POST:
                    # redirect to manage students url.
                    return redirect('adminhod:manage-student')
            # create new staff.
            elif user_type == 'STAFF':
                new_user.staff.photo = form.cleaned_data.get("photo")
                new_user.staff.birth_date = form.cleaned_data.get("birth_date")
                new_user.staff.nationality = form.cleaned_data.get("nationality")
                new_user.staff.phone = form.cleaned_data.get("phone")
                new_user.staff.address = form.cleaned_data.get("address")
                new_user.staff.gender = form.cleaned_data.get("gender")
                new_user.staff.recruitment_date = form.cleaned_data.get("recruitment_date")
                new_user.staff.save()
                # Display success message.
                messages.success(request, f'New Staff "{full_name}" has been added successfully.', extra_tags='add-staff')
                # if save and add another.
                if 'save_and_add_another' in request.POST:
                    # redirect to add staff url.
                    return redirect('adminhod:add-staff')
                # if save.
                elif 'save' in request.POST:
                    # redirect to manage staff url.
                    return redirect('adminhod:manage-staff')

    context = {'is_admin':is_admin, 'user_form':user_form, 'form':form}
    return render(request, template_name, context)

def update_staff_student_form(request, form, template_name, staff_student):
    """
    Take form, template name, and staff or student.
    Update staff in case of taking staff.
    Update student in case of taking student.
    """
    # display initial data of student or staff.
    user_form = UpdateUserForm(
        request.POST or None,
        staff_student=staff_student, 
        instance=staff_student, 
        initial={'full_name': staff_student.user.full_name,
                 'email': staff_student.user.email, 
        })
    data = dict()
    is_update = True
    is_admin = True
    staff_student_name = staff_student.user.full_name
    if request.method == 'POST':
        if user_form.is_valid() and form.is_valid():
            # update student or staff.
            form.save()
            staff_student.user.full_name = user_form.cleaned_data.get('full_name')
            staff_student.user.email = user_form.cleaned_data.get('email')
            staff_student.user.save()
            data['form_is_valid'] = True
            data['is_update'] = True
            # update student.
            if staff_student.user.user_type == 'STUDENT':
                # get all students.
                students = Student.objects.all()
                data['html_student_list'] = render_to_string('student/includes/partial_student_list.html', {'students': students})
                data['student_name'] = staff_student_name
            # update staff.    
            elif staff_student.user.user_type == 'STAFF': 
                # get all staffs.  
                staffs = Staff.objects.all()
                data['html_staff_list'] = render_to_string('staff/includes/partial_staff_list.html', {'staffs': staffs})
                data['staff_name'] = staff_student_name
        else:
            data['form_is_valid'] = False
    context = {'is_update':is_update, 'is_admin':is_admin, 'user_form':user_form, 'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)

def add_staff(request):
    """
    Add staff.
    """
    user_type = 'STAFF'
    if request.method == 'POST':
        staff_form = AddStaffForm(request.POST, request.FILES)
    else:
        staff_form = AddStaffForm()
    return add_staff_student_form(request, staff_form, 'staff/add_staff.html', user_type)

def manage_staff(request):
    """
    Display all staffs of current adminhod's courses.
    Search staff by name or email, ordered alphabetically by name.
    """    
    # get list of all staffs' ids of current adminhod's courses.
    staffs_ids_list = Subject.objects.staff_ids(request.user)
    # get all staffs of current adminhod's courses.
    staffs_qs = Staff.objects.filter(user__id__in=staffs_ids_list)
    # get all courses of current adminhod.
    courses = Course.objects.filter(adminhod__user__id=request.user.id)
    # paginate the staffs list.
    page_obj_staffs = paginate(staffs_qs)
    if request.is_ajax():
        # get entered value in search input field.
        q = request.GET.get('search').strip()
        data = dict()  
        # filter staff by name or email, ordered alphabetically by name.
        staffs = search(q, staffs_qs)
        # paginate the staffs list.
        page_obj_staffs = paginate(staffs)    
        context = {'staffs': page_obj_staffs, 'request':request}
        data['html_staff_list'] = render_to_string('staff/includes/partial_staff_list.html', context)
        data['html_staff_pagination'] = render_to_string('staff/includes/partial_staff_pagination.html', context)
        return JsonResponse(data)
    context = {'staffs':page_obj_staffs, 'courses':courses}
    return render(request, 'staff/manage_staff.html', context)

def paginate_staff(request):
    """
    Paginate all staffs of current adminhod's courses.
    """
    # get list of all staffs' ids of current adminhod's courses.
    staffs_ids_list = Subject.objects.staff_ids(request.user)
    # get all staffs of current adminhod's courses.
    staffs_qs = Staff.objects.filter(user__id__in=staffs_ids_list)
    # get page number of paginator.
    page_number = request.GET.get('page').split('&')[0]
    # get course id.
    course_id = request.GET.get('course_id')
    # get student gender.
    gender = request.GET.get('gender')
    # get list of submitted data.
    list_data = [course_id, gender]
    data = dict()
    # paginate the search results.
    if request.GET.get('search'):
        # get entered value in search input field.

feedback/templates/staff/add_feedback_staff.html
{% extends 'base.html' %}

{% block title %}
<title>Add Feedback</title>
{% endblock title %}

{% block content %}

<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            {% include 'staff/dashboard_includes/left_navbar.html' %}

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
        
                <!-- Notifications Dropdown Menu -->
                {% include 'staff/dashboard_includes/notifications_dropdown.html' %}

            </ul>
        </nav>
        <!-- /.navbar -->

        <!-- Main Sidebar Container -->
        {% include 'staff/dashboard_includes/main_sidebar.html' %}

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark">Add Feedback</h1>
                        </div><!-- /.col -->
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="{% url 'staff:dashboard' %}">Home</a></li>
                                <li class="breadcrumb-item active">Add Feedback</li>
                            </ol>
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->

            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                    <div class="row">
                        <!-- left column -->
                        <div class="col-md-12">
                            <!-- general form elements -->
                            <div class="card card-primary">
                                <div class="card-header">
                                    <h3 class="card-title">Leave a Feedback</h3>
                                </div>
                                <!-- /.card-header -->
                                <!-- Display success message -->
                                {% if messages %}
                                    {% for message in messages %}
                                        {% if 'add-feedback-staff' in message.tags %}
                                            <div class='alert alert-success message mt-2'>{{ message }}</div>
                                        {% endif %}
                                    {% endfor %}
                                {% endif %}  
                                <!-- form start -->
                                <form role="form" action='.' method='POST'>
                                    {% csrf_token %}
                                    <div class="card-body">
                                        <div class="form-group">
                                            <label>Feedback message</label>
                                            <textarea class='form-control' rows='6' name='feedback_message' placeholder='Leave a Feedback...' style="resize: none;" required></textarea>
                                        </div>
                                    </div>
                                    <!-- /.card-body -->

                                    <div class="card-footer d-flex justify-content-end">
                                        <button type="submit" name='save_and_add_another' class="btn btn-primary mr-1">Save and add another</button>
                                        <button type="submit" name='save' class="btn btn-primary">Save</button>
                                    </div>
                                </form>
                            </div>
                            <!-- /.card -->
                        </div>
                    </div>
                </div>
            </section>
        </div>
        <!-- /.content-wrapper -->

        <!-- Footer Container -->
        {% include 'adminhod/dashboard_includes/footer.html' %}

    </div>
    <!-- ./wrapper -->

    <!-- scripts -->
    {% include 'staff/scripts_includes/add_feedback_staff_js.html' %}

</body>

{% endblock content %}

feedback/templates/staff/feedback_detail_staff.html
<!-- modal header -->
<div class="modal-header">
    <h4 class="modal-title">Feedback</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<!-- modal body -->
<div class="modal-body">
    <div class="card-body">
        <div class="form-group">
            <label>Feedback</label>
            <div class='form-control' style="cursor: not-allowed;"><p>{{ feedback.content }}</p></div>
        </div>
        <div class="form-group">
            <label>Reply</label>
            {% if feedback.reply %}
            <div class='form-control' style="cursor: not-allowed;"><p>{{ feedback.reply }}</p></div>
            {% else %}
            <div class='form-control' style="cursor: not-allowed;"><p>No Reply</p></div>
            {% endif %}
        </div>    
    </div>
    <!-- /.card-body -->
</div>
<!-- modal footer -->
<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>

feedback/templates/staff/view_feedback_staff.html
{% extends 'base.html' %}

{% block title %}
<title>Feedback</title>
{% endblock title %}

{% block content %}

<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            {% include 'staff/dashboard_includes/left_navbar.html' %}

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <!-- Notifications Dropdown Menu -->
                {% include 'staff/dashboard_includes/notifications_dropdown.html' %}

            </ul>
        </nav>
        <!-- /.navbar -->

        <!-- Main Sidebar Container -->
        {% include 'staff/dashboard_includes/main_sidebar.html' %}

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark">Feedback</h1>
                        </div><!-- /.col -->
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="{% url 'staff:dashboard' %}">Home</a></li>
                                <li class="breadcrumb-item active">Feedback</li>
                            </ol>
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->

            <!-- Main content -->
            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-12">
                            <div class="card card-solid" style='width: 100%;'>
                                <div class="d-flex align-items-center justify-content-between flex-wrap">
                                    <!-- Filter  -->
                                    <div class='d-flex flex-wrap flex-grow-1'>
                                        <select class="custom-select d-flex flex-grow-1 flex-md-grow-0 m-1 m-lg-2"
                                            style="width: auto;" name='is-replied'
                                            id='staff-feedback-filter-by-reply'>
                                            <option value="" selected>Sort by Reply</option>
                                            <option value='1'>Replied</option>
                                            <option value='0'>Unreplied</option>
                                        </select>
                                        <div class="btn-group d-flex flex-grow-1 flex-md-grow-0 m-1 m-lg-2">
                                            <button type="submit" name='save' class="btn btn-default"
                                                id='staff-feedback-filter'>Filter</button>
                                        </div>
                                    </div>
                                    <!-- Search  -->
                                    <div class="card-tools d-flex flex-grow-1 flex-md-grow-0 mx-1 mx-lg-2 my-3 my-lg-2"
                                        style="min-width: 280px; min-height: 38px;">
                                        <div class="input-group input-group-sm">
                                            <input type="text" name="table_search" class="form-control float-right"
                                                style="height: 100%;" id='feedback-staff-search'
                                                placeholder="Search by Date 'yyyy-mm-dd'">

                                            <div class="input-group-append">
                                                <button type="submit" class="btn btn-default"><i
                                                        class="fas fa-search"></i></button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card">
                                <!-- Table -->
                                <div class="card-body table-responsive p-0">
                                    <table class="table table-hover text-nowrap" id='feedback-staff-table'>
                                        <thead>
                                            <tr>
                                                <th>Date</th>
                                                <th>Feedback</th>
                                                <th>Reply</th>
                                                <th>View</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% include 'staff/includes/partial_feedback_staff_list.html' %}
                                        </tbody>
                                    </table>
                                </div>
                                <!-- /.card-body -->
                                <div id='feedback-staff-paginator'>
                                    {% include 'adminhod/includes/partial_feedback_adminhod_pagination.html' %}
                                </div>
                                <!-- /.card-footer -->
                            </div>
                            <!-- /.card -->
                        </div>
                    </div>
                    <!-- /.row -->
                </div>
            </section>
        </div>
        <!-- /.content-wrapper -->

        <!-- Staff Feedback Modal -->
        <div class="modal fade" id="modal-feedback-staff">
            <div class="modal-dialog">
                <div class="modal-content">
                </div>
                <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div>
        <!-- /.modal -->

        <!-- Footer Container -->
        {% include 'adminhod/dashboard_includes/footer.html' %}

    </div>
    <!-- ./wrapper -->

    <!-- scripts -->
    {% include 'staff/scripts_includes/view_feedback_staff_js.html' %}

</body>

{% endblock content %}